services:
  postgres:
    image: postgres:16-alpine
    container_name: forget_ex_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: forget_ex_redis
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - ./redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: forget_ex_bot
    env_file: .env
    volumes:
      - ./api:/app/api
      - ./bot:/app/bot
      - ./logs:/app/logs
      - ./media:/app/media
      - ./shared:/app/shared
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: forget_ex_api
    env_file: .env
    volumes:
      - ./api:/app/api
      - ./bot:/app/bot
      - ./logs:/app/logs
      - ./media:/app/media
      - ./shared:/app/shared
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api
